from enum import Enum

class AllureTag(str, Enum):
    USER_LOGIN = 'USER_LOGIN'
    REGISTRATION = 'REGISTRATION'
    AUTHORIZATION = 'AUTHORIZATION'

    GET_ENTITY = 'GET_ENTITY'
    GET_ENTITIES = 'GET_ENTITIES'
    CREATE_ENTITY = 'CREATE_ENTIT'
    UPDATE_ENTITY = 'UPDATE_ENTITY'
    DELETE_ENTITY = 'DELETE_ENTITY'
    DELETE_ENTITIES = 'DELETE_ENTITIES'
    VALIDATE_ENTITY = 'VALIDATE_ENTITY'

